version: 0.2

phases:
  install:
    commands:
      # remove package-lock before updating npm, otherwise not all dependencies will install
      - rm package-lock.json
      # update npm to 5.6.0 due to package-lock bug: https://github.com/npm/npm/issues/18135
      - npm install --silent --progress=false -g npm
      # install dependencies
      - npm install --silent --progress=false -g serverless
      - npm install --silent --progress-false
      - npm --version
  build:
    commands:
      # linting and unit tests
      - npm run-script lint
      - npm test
      # deploy integration testing environment
      - serverless deploy --stage test -v
      # integration tests
      - npm run-script integration
      # if successful, create packages for staging and prod
      # - serverless deploy --stage staging -v
      - mkdir artifacts
      # staging
      - mkdir artifacts/staging
      - serverless package --package artifacts/staging --stage staging -v
      # prod
      - mkdir artifacts/prod
      - serverless package --package artifacts/prod --stage prod -v
  post_build:
    commands:
      # tear down integration testing environment
      - serverless remove --stage test -v

artifacts:
  files:
    # export artifacts needed for staging and prod deployments to an S3 bucket
    - serverless.yml
    - artifacts/**/*
    - deploy.sh
    # - package.json
