---
version: 0.2

phases:
  install:
    commands:
      # remove package-lock before updating npm, otherwise not all dependencies will install
      - rm package-lock.json
      - npm install --silent --progress=false -g npm
      - npm install --silent --progress=false -g serverless
      - npm install --silent --progress-false
      - npm --version
  build:
    commands:
      # linting and unit tests
      - npm run-script lint
      - npm test
      # deploy integration testing environment
      - serverless deploy --stage test | tee deploy.out
      - cat deploy.out
      - npm run-script integration
      # if successful, deploy to staging environment
      # - serverless deploy --stage staging -v
  post_build:
    commands:
      - serverless remove --stage test -v
      - echo 'foo'
...
