// tests for listTodos
// Generated by serverless-jest-plugin

const mod = require('./../todos/handler');
const jestPlugin = require('serverless-jest-plugin');

const lambdaWrapper = jestPlugin && jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'list' });

describe('listTodos', () => {
  beforeAll((done) => {
  // lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('should return 200', () => {
    return wrapped.run({}).then((response) => {
      console.error(response);
      expect(response.statusCode).toBe(200);
    });
  });
});
